### PR TITLE
Refactor `searchInPairs` and Enhance `rtrimLines` Functions

### PR DESCRIPTION
**Pull request by Mefisto04**
This pull request includes the following changes:

1. **Refactored `searchInPairs`**:
   - Simplified the binary search logic for determining if a `hashIndex` falls within string literal pairs. This enhances code readability and maintainability.

2. **Enhanced `rtrimLines` Function**:
   - Modified the implementation to utilize `String.prototype.trimEnd()` for trimming trailing whitespace from each line, improving performance and efficiency.

These changes aim to streamline the code while maintaining the existing functionality and ensuring that all tests pass successfully.

## Summary by CodeRabbit

- **New Features**
	- Simplified methods for removing docstrings and hash comments in Python files, improving efficiency.
	- Introduced a new function to manage the instantiation of file manipulators based on file extensions.

- **Refactor**
	- Enhanced clarity and maintainability of code by streamlining comment removal logic.
	- Updated the line trimming method to improve readability and efficiency.
	- Retained the `CompositeManipulator` class while restructuring manipulator instantiation and access.

### CODE REVIEW

**Comment by yamadashy** [comment]
@Mefisto04 
Thank you for your quick implements! 

However, it seems that the lint checks and tests are currently failing. Could you please take a look and address the following:

1. Resolve any lint errors. `npm run lint`
2. Fix the failing tests. `npm run test`

Thanks again for your contributions to improving Repopack's performance.

**Comment by Mefisto04** [comment]
image
image

**Comment by yamadashy** [comment]
I see that secretlint is throwing an error.
Are you perhaps using Windows? It might be an issue with path separators.

**Comment by Mefisto04** [comment]
@yamadashy yes, i am using windows.
so what will be the approach to solve this ? Coz there is no issue in test when i run that

**Comment by yamadashy** [comment]
I've committed the lint fixes to your branch.
Additionally, I've merged a fix into the main branch that addresses the issue with secretlint not running properly on Windows.

Let me know if you encounter any further issues. Thanks for your patience and contribution!

**Comment by yamadashy** [comment]
Hi, @Mefisto04 

The implementation is perfect, thank you so much! 
Your changes have significantly improved the code's readability and efficiency.

I'll merge this!

**Pull request merged**
